### PR TITLE
Correcting columns to singular column names: #453

### LINKED ISSUE #453: Correct column names to singular
Our standard is to use singular column names even though a field may contain multiple values. 
The following column names from SCWB v3.1.1 should be reset to singular:
- Copyright Statements
- Copyright Holders
- Copyright Authors
- License Expressions
- Scan Errors

### PR DESCRIPTION
**Pull request by pranav1698**
This renames the columns in the ScanCode data table to single names.
I have changed the columns that were mentioned in the issue #453,
I can change other if needed

Closes #453

### CODE REVIEW

**Review by steven-esser — CHANGES_REQUESTED** [review]
From what I understand of #453, I think we want to keep the "Copyright" string and just make the entire string singular.

For example `Copyright Statements` should be `Copyright Statement`. Same thing for the other columns mentioned in #453

**Comment by pranav1698** [comment]
@majurg oh, will update it accordingly

**Comment by pranav1698** [comment]
@majurg please review now

**Review by steven-esser — CHANGES_REQUESTED** [review]
@pranav1698 The code changes are now correct, however you have added a `yarn.lock` file to this commit. We do not use yarn, so can you please remove it?

**Comment by pranav1698** [comment]
will remove @majurg

**Review by steven-esser — APPROVED** [review]

**Comment by steven-esser** [comment]
@pranav1698 Thanks!

**Pull request merged**
