### PR TITLE
adding hamburger menu

### LINKED ISSUE #437: Hamburger Menu for Expand and Collapse of Side Menu Bar
### Description
The side menu bar should have an expand-collapse enabling button so that new users can use it to understand what all the options present mean. 

Capture (1)

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
## Description

I have adding hamburger menu which look nice to me. This will fixes #437 .

https://user-images.githubusercontent.com/59874304/106004441-3b0fe800-60d9-11eb-9700-91dcc26d4e42.mp4

@majurg have a look at this !! @nitin10s any improvement you want ?

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@majurg any update on this PR or improvement I can do ?

**Comment by Vishal-raj-1** [comment]
@majurg any update on this PR or improvement I can do ?

**Review by nitin10s — COMMENTED** [review]
Please provide some margin on the left of the menu heading text. Also please give the vertical hr present between icon and heading (Refer to design)

**Comment by Vishal-raj-1** [comment]
> Please provide some margin on the left of the menu heading text. Also please give the vertical hr present between icon and heading (Refer to design)

sure !!

**Comment by Vishal-raj-1** [comment]
@nitin10s is this fine ?

https://user-images.githubusercontent.com/59874304/106272232-b9de5f80-6256-11eb-856a-c9f4ae59e7d0.mp4

**Comment by Vishal-raj-1** [comment]
I have increase the margin left of menu heading text little more. Check it now if it look nice then I will commit and push my changes.

final preiview

**Review by steven-esser — CHANGES_REQUESTED** [review]
This is a good, thank you for the contribution. 

I have a few items that would be nice to change:
* The menu should not be show on first load/reload. It should be hidden by default until the hamburger icon is clicked.
* The expanded menu should be border-less since we have a highlight action on mouse over. Currently there is a white border between the icons and the text; it would look better without this (at least in my opinion.)

**Comment by Vishal-raj-1** [comment]
@majurg Done . Check it now !!

https://user-images.githubusercontent.com/59874304/106350063-11cda280-62f9-11eb-915d-7a3ee9411716.mp4

**Review by nitin10s — APPROVED** [review]
Looks great!

**Comment by Vishal-raj-1** [comment]
> Looks great!

Thanks 😊

**Review by steven-esser — CHANGES_REQUESTED** [review]
The content looks good here.

There is a linting error here: https://travis-ci.org/github/nexB/scancode-workbench/jobs/756810900#L1195-L1222

Please correct this and then I can merge.

**Comment by Vishal-raj-1** [comment]
> The content looks good here.
> 
> There is a linting error here: https://travis-ci.org/github/nexB/scancode-workbench/jobs/756810900#L1195-L1222
> 
> Please correct this and then I can merge.

Sure !!

**Comment by Vishal-raj-1** [comment]
@majurg done !!

**Review by steven-esser — CHANGES_REQUESTED** [review]
There is still linting errors... see: https://travis-ci.org/github/nexB/scancode-workbench/jobs/757096674#L1200-L1205

If you run `npm test` before pushing, you can catch all of these yourself before travis does. Please do this in the future.

**Comment by Vishal-raj-1** [comment]
> If you run `npm test` before pushing, you can catch all of these yourself before travis does. Please do this in the future.

Sure !! I will keep it in mind.

**Comment by Vishal-raj-1** [comment]
@majurg Sir Can you squash and merge from your side. When I am trying to do they cause merge conflicts.

**Comment by steven-esser** [comment]
@Vishal-raj-1 This PR is from your fork, so I cannot make modifications on my side. 

Fixing the merge conflict should not be too difficult, though I understand it can be intimidating at first. Check out resources like https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line or google search if you want more resources.

**Review by steven-esser — APPROVED** [review]
The content looks good here. I will hold of merging until your commits are squashed and conflicts resolved.

**Pull request closed without merging**
