### PR TITLE
issue-template

### PR DESCRIPTION
**Pull request by Dinesh101041**
Signed-off-by: Dinesh <dinesh101041@gmail.com>

Fixe : #486

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@Dinesh101041 Can you please comment out reference messages for contributors and also add some stuff in documentation template.

**Comment by Dinesh101041** [comment]
What to add in documentation can you tell briefly i am ready to make a change sir

**Comment by Aayush-hub** [comment]
> What to add in documentation can you tell briefly i am ready to make a change sir


Something like this works.

**Comment by Dinesh101041** [comment]
Changed the documentation sir please check

**Comment by Aayush-hub** [comment]
> Changed the documentation sir please check

@Dinesh101041 Looks fine, also comment out the reference messages. Don't put them with bullet marks, put them under markdown comments.

**Comment by Dinesh101041** [comment]
i think bullet point is better sir

**Comment by Aayush-hub** [comment]
> i think bullet point is better sir

@Dinesh101041 The contributors has to edit the bullet points or delete it if they didn't want it. But for reference messages I think comments is good because the contributor gets the reference without editing or deleting it. Even if they want the message to appear on the issue, they can copy paste the same.
@majurg Sir what do you think?

**Comment by OmkarPh** [comment]
Thanks for the PR @Dinesh101041 
We've refactored the workbench in the past year, and have an Isuue template covering text regarding bugs & feature requests. I don't think we need these many options.

Feel free to open a new PR with a slimmer issue template :)

**Pull request closed without merging**
