### PR TITLE
I have fixed grammatical errors

### PR DESCRIPTION
**Pull request by Abhigyankrsingh**
I have fixed grammatical errors in LICENSE and in NOTICE according to the issue ( issue #465 )

### CODE REVIEW

**Comment by Abhigyankrsingh** [comment]
can anyone tell me why i am getting this error?

**Comment by steven-esser** [comment]
@Abhigyankrsingh These changes are not relevant and many of them are simply incorrect. I am closing this.

If you are interested in contributing to the project, please take a look the issues page: https://github.com/nexB/scancode-workbench/issues

**Comment by Abhigyankrsingh** [comment]
@majurg  Sir, there were some grammatical mistakes in those files,that's why i wanted to correct them and i wanted to update them.

**Comment by mjherzog** [comment]
@Abhigyankrsingh Thank you for your interest, but the changes you suggested are more about style than correctness.

**Comment by Abhigyankrsingh** [comment]
thanks,  @majurg , and @mjherzog  for your time

**Pull request closed without merging**
