### PR TITLE
License clues section in Licenses explorer

### LINKED ISSUE #565: Also show license clues
### Description

We don't show `resource.license_clues` currently but this is required too in the license detections explorer.

Consider the following scan:
[bcpg-fips-1.0.4.jar-v32rc4results.json.txt](https://github.com/nexB/scancode-workbench/files/11337035/bcpg-fips-1.0.4.jar-v32rc4results.json.txt)

There is a license clue detection at `bcpg-fips-1.0.4.jar-extract/META-INF/BC2048KE.DSA`

like this:

```
"detected_license_expression": null,
      "detected_license_expression_spdx": null,
      "license_detections": [],
      "license_clues": [
        {
          "score": 8.93,
          "start_line": 43,
          "end_line": 43,
          "matched_length": 5,
          "match_coverage": 8.93,
          "matcher": "3-seq",
          "license_expression": "ipa-font",
          "rule_identifier": "ipa-font_5.RULE",
          "rule_relevance": 100,
          "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/ipa-font_5.RULE",
          "matched_text": "constitutes acceptance of the [DigiCert] [CP]/[CPS] [and] [the] [Relying] [Party] Agreement"
        }
```

This should be displayed similar to how other dependencies are shown in package explorer, they are in another section down below, but looks exactly like the other license detections. I.e.

there would be one entry on the left for each license match, and one entry in the license match table in the right, and the file region in the corresponding table.

### PR DESCRIPTION
**Pull request by OmkarPh**
Fixes #565

### CODE REVIEW

**Review by AyanSinhaMahapatra — APPROVED** [review]
@OmkarPh looks good thanks++
I've tested out with the scan in the issue and this works as expected. Couple of follow ups:
1. Possible UI improvements?
license-clues
The horizontal and vertical scrollbars are present always here, on the left pane.
workbench-packages-feel
In packages view these scrollbars are only present when we have a lot of packages/dependencies or we expand the dependencies and there is scrolling.
IMHO the scrollbars should only be present when scrolling is possible.
This is also present in other views like the packages explorer.


2. Grouping same license clues together.

This has to happen from the toolkit side, I'm thinking of adding a new field in the license clues : `for_detection` as a refinement to be able to group these together. This will be useful where there are a bunch of repeating license clues. We'll then do the needful here to have them similarly as the matches table in license detections then.

**Comment by OmkarPh** [comment]
I couldn't reproduce the ugly empty scroll panes on my system (maybe it's OS specific 🤔 )
I've pushed a trial fix, please test it on your system

**Comment by AyanSinhaMahapatra** [comment]
> maybe it's OS specific thinking )

Yeah thought so, these are fixed now! See screenshots below.

ugly-bars-fixed-license
ugly-bars-fixed-packages

**Review by AyanSinhaMahapatra — APPROVED** [review]
LGTM! Thanks!

**Comment by OmkarPh** [comment]
> > maybe it's OS specific thinking )
> 
> Yeah thought so, these are fixed now! See screenshots below.

thanks 😄

**Pull request merged**
