### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by divya814**
Improved documentation by removing the "Import a JSON file" GIF which was not working. Done some sentence corrections.

### CODE REVIEW

**Comment by pratik0316** [comment]
Hi @divya814 
Please sign off your commits for the DCO

**Comment by divya814** [comment]
Hi @Pratikrocks , can you please help me with this? Kindly tell me where I have to run these two suggested commands.

**Comment by pratik0316** [comment]
First rebase all commits to a single commit then , just put the flag -s when you are making the commit, to correct DCO .
Its is better to use the CLI always
You can follow this https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by divya814** [comment]
Thank you so much, I will try to resolve the issue asap.

**Pull request closed without merging**
