### PR TITLE
Move filter bar to the top in table view

### LINKED ISSUE #271: Move filter bar to top of page
The bar with column filters is currently displayed at the bottom of the Table View window, separate from the Column visibility and Search buttons at the top. It might be more logical and useful to display the Filter bar below the current Column visibility / Search bar.

### PR DESCRIPTION
**Pull request by lakshay-angrish**
Fixes #271 
The table view now has all filters at the top

ss

### CODE REVIEW

**Review by steven-esser — CHANGES_REQUESTED** [review]
Two things:
1) I would prefer that the buttons controlling filter actions ("Activate Filters", etc) be visually different, separate buttons from the rest of the column view buttons. 

2) Every time I go to select a value from the filter drop-downs, a column sort is triggered. This is not a behavior we want to have.

**Comment by lakshay-angrish** [comment]
@majurg I have made the suggested changes and updated the screenshot in the PR Description.

**Review by steven-esser — CHANGES_REQUESTED** [review]
This is much better and we are almost there :)

One last request: Can you please style the filter buttons as buttons, not just links? 

All in all, I still want these to be buttons, just not identical buttons to the column view buttons. 

Does this make sense?

**Comment by lakshay-angrish** [comment]
@majurg I understand. It is still a button though, just with the `btn-link` class. Which bootstrap button class should I assign?

**Comment by steven-esser** [comment]
A standard bootstrap button is fine I think

**Comment by lakshay-angrish** [comment]
@majurg Since it is a part of buttons[] in the DataTable, it is already applied with `btn btn-default`. Do you have any tips on how to remove/override it?

**Comment by lakshay-angrish** [comment]
@majurg Made the buttons look like before this PR, and updated the screenshot.

**Review by steven-esser — APPROVED** [review]
Looks good, thanks for this.

**Pull request merged**
