### PR TITLE
Create new icons #382

### PR DESCRIPTION
**Pull request by johnmhoran**
* Created .png (Linux) and .ico (Windows) but .icns for macOS not yet created.

Signed-off-by: John M. Horan <johnmhoran@gmail.com>

### CODE REVIEW

**Comment by johnmhoran** [comment]
@majurg I've added icons for Linux and Win and code for Linux, Win and macOS -- but have not created the .icns for macOS.  Please let me know what you think, and what changes if any you suggest, when you have the chance.

**Review by steven-esser — CHANGES_REQUESTED** [review]
@johnmhoran Can you also add the source file you used to generate the various sizes/types etc? Once this is added I can create the macos `.icns` file.

**Comment by johnmhoran** [comment]
@majurg For the current proposed icon I have a krita source file named `scwb_blue_square_02.ico.kra` -- shall I add that to one of the `/app-icon/` folders and do another commit and push?

**Comment by steven-esser** [comment]
Preferably, we would want the source to be in `.svg` format as this is portable and easily convertible. 

I am not sure if you created the icon yourself or got it from another location, but you should be able to save/export the file to `.svg` format in krita

**Comment by johnmhoran** [comment]
@majurg I used a single vector layer rather than the default canvas -- `.svg` file can be found in `/app-icon/mac/` folder.

**Comment by steven-esser** [comment]
@johnmhoran Looks like we can use just a `.png` file to generate the MacOS `.icns` file. Sorry about that. 
In my latest commit, I added the `icns` file for MacOS and removed the unnecessary svg file.

**Review by steven-esser — APPROVED** [review]

**Pull request merged**
