### PR TITLE
Diff modal for Matched text & Rule text in Matches table

### LINKED ISSUE #561: View the matched text of a license match
### Description
When I review a license scan with license matches (and --license-text) I would like to view the actual match text for each match

As a refinement, I would like to also see highlighted the non matched parts by displaying a visual diff against the matched RULE text.

With this feature, I would be able to validate the correctness of a license match without having the scanned codebase on hand.

Notes: for the diff, we could use diff-match-patch that has both a Python and a JS implementation.

### PR DESCRIPTION
**Pull request by OmkarPh**
Fixes #561

### CODE REVIEW

**Comment by OmkarPh** [comment]
The matched_text is hidden for scans without `license-text` 

Here's a screenshot of diff 
image

**Comment by AyanSinhaMahapatra** [comment]
I have a couple of suggestions here:

On the window:

* In the diff modal, show the `Matched Coverage` instead of the `Score`
* I don't get why we are having the texts displayed two times each

On the diff (just putting points from our discussion in the community call here):

* We should ignore special characters (Unless it's a `+` after a word, like `gpl3+` or similar)
diff-special-characters
* We are not matching correctly texts in different lines
text_lines

Maybe we do some pre-processing before the diff?

Otherwise this is looking great. Thanks++

**Comment by AyanSinhaMahapatra** [comment]
A good example with many variations to test this on.s
[aws-java-sdk-core-1.12.262-sources.jar-v32rc4results-todo.json.txt](https://github.com/nexB/scancode-workbench/files/11690749/aws-java-sdk-core-1.12.262-sources.jar-v32rc4results-todo.json.txt)

Notice also the matched text sometimes has `[]` which are diagnostics elements from `scancode-toolkit`. This would be moved to a different attribute to fix this: https://github.com/nexB/scancode-toolkit/issues/3426

**Comment by OmkarPh** [comment]
> I have a couple of suggestions here:
> 
> On the window:
> 
> * In the diff modal, show the `Matched Coverage` instead of the `Score`
> * I don't get why we are having the texts displayed two times each

Actually, I had opened this PR before the call this week, the diff you see below is what we discussed in the call (it has unnecessary diffs like spaces, newlines, etc)

The diff on top is the final diff we will have.
I kept older diff for now to just compare how the updated diff works. 


> * We are not matching correctly texts in different lines
That was the case in old diff in bottom, in newer one, it must be fixed. Yet, there can be unnoticed edgecases :)

**Comment by OmkarPh** [comment]
hi @AyanSinhaMahapatra 
you can test now, i've removed debug setup, and handled some edge cases

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh tested out the diffs, this is looking great! Much more improved from before and works great on most cases!

There are a couple more edge case to handle btw:

- The case where we have a match to a `.LICENSE` file instead of a `.RULE` file. In this case we should fetch the rule text from the specific entry in the `license_references` list instead of the `license_rule_references` list. For now this is showing the following:
license-rule-diff-case

- Sometimes there is a diff shown on words when there are extra special characters preceding them in the match side, see one example here:
diff-edge-case-symbols

Testing this out more, but once this is working great on most of the cases, we can merge and track more edge cases separately in the issue.

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh 

> The case where we have a match to a .LICENSE file instead of a .RULE file. In this case we should fetch the rule text from the specific entry in the license_references list instead of the license_rule_references list. 

Ignore this part ^. This is being handled correctly. The result JSON did not have any license references data so that's why it showed that.

One other point on that btw:

let's say in the matched text/diff modal when we don't have references data, instead of saying: `Couldn't find License Rule Reference for specified identifier - mit_14.RULE` we should say something like: `Please use --license-references CLI option with your scan to see the rule text, and the diff between rule/matched text.` Also use this link: https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/scan-options-post.html#license-references-option

Similarly there are cases where there are no rule texts, as we create synthetic rules for showing matches:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/models.py#L2310
These have the following identifier-prefixes:

`spdx-license-identifier`: matches to SPDX license expressions with a prefix like `SPDX-License-Identifier:` which signifies that there are SPDX license expressions following these prefixes.
`license-detection-unknown`: these are license detections which are not matched properly and cannot be concluded to a license-expression.
`package-manifest-unknown`: These are license statements in package manifests which cannot be matched properly to a license expression.

For these three cases of synthetic rules we can have seperate doc strings which can be shown.

**Comment by OmkarPh** [comment]
I've handled the mentioned cases with relevant messages (let me know if the text needs any change)
Also, fixed the diff errors & some UI changes to handle text-overflow

**Review by AyanSinhaMahapatra — APPROVED** [review]
@OmkarPh LGTM! thanks++
This works perfectly thanks! I've tested out the new changes and all the issues in the comments above are resolved. This is ready to merge.

**Pull request merged**
