### PR TITLE
Refactor to v4.0 react typescript & schema updates upto sct v32.x

### PR DESCRIPTION
**Pull request by OmkarPh**

### CODE REVIEW

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh btw, for future commits, if there is an open issue we have in workbench that you are addressing/fixing (either partially or fully), please reference the issue in your commit so they are linked and visible from each other PR <-> Issue.

**Comment by OmkarPh** [comment]
> @OmkarPh btw, for future commits, if there is an open issue we have in workbench that you are addressing/fixing (either partially or fully), please reference the issue in your commit so they are linked and visible from each other PR <-> Issue.

alright

**Review by AyanSinhaMahapatra — APPROVED** [review]
@OmkarPh LGTM!
Just one small update required:
The gif at https://github.com/nexB/scancode-workbench/blob/v4.0-react-typescript/README.md?plain=1#L18 seems to be outdated, maybe we have some asset on the latest workbench that we can reuse from the docs or somewhere else here?
Otherwise let's merge and release a stable version.
https://github.com/nexB/scancode-workbench/issues/607, https://github.com/nexB/scancode-workbench/pull/610 and other UI updates can be added later.

**Comment by OmkarPh** [comment]
Thanks @AyanSinhaMahapatra 
Finally, merging into develop !!

**Pull request merged**
