### PR TITLE
Build filetree with missing directories to support --only-findings scans

### LINKED ISSUE #393: view "Directory Tree" does not work
### Description
The view "Directory Tree" does not work, I only see the top directory of my scan. If I want to open/expand it, a "Processing.." pops up very short and the "expand icon" dissapears. 
Are there any known issues?
Do I have to consider anything (e.g. dir of json-file, dir of running scancode-workbench)?

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
Ubuntu 18.04.2 LTS
* What version of scancode-workbench are you running on?
Scancode Workbench Version 3.1.0 (build from develop branch - commit 2cd0d32)
* What version of scancode-toolkit was used to generate the scan file?
ScanCode version: 3.1.1

### LINKED ISSUE #404: Handle scancode output files that include `--only-findings`
Originally reported here: https://github.com/nexB/scancode-workbench/issues/393

When a scancode results file has the `--only-findings` option present, data gets loaded into the database but the Tree View itself does not get created properly. 

scancode-workbench should support the proper loading of scans that include the `--only-findings` option.

### PR DESCRIPTION
**Pull request by OmkarPh**
Fixes #404 #393 

- Handles scans with `--only-findings` option by imputing required intermediate directories
- Fixed root path resolution for cases like empty scans.

Reference scans - 
[allsamples-onlyfindings.json.txt](https://github.com/nexB/scancode-workbench/files/13883213/allsamples-onlyfindings.json.txt)
[allsamples-onlyfindings-noresources.json.txt](https://github.com/nexB/scancode-workbench/files/13883214/allsamples-onlyfindings-noresources.json.txt)

### CODE REVIEW

**Review by AyanSinhaMahapatra — CHANGES_REQUESTED** [review]
@OmkarPh thanks++ 
Looks good and needs a couple more edge-cases handling, based on problems detected in larger scans.

Consider the following scans:

[postgresml-2.8.1.json](https://github.com/nexB/scancode-workbench/files/13888926/postgresml-2.8.1.json)
[postgresml-2.8.1-only-findings.json](https://github.com/nexB/scancode-workbench/files/13888929/postgresml-2.8.1-only-findings.json)

See comments below:

1. In the only-findings scan, the file-tree is not behaving correctly for nested directories (as the corresponding parent directories are missing?) should we populate missing parent directories ourself while importing the scan? Example resource: `"postgresml-2.8.1/pgml-cms/docs/resources/benchmarks/mindsdb-vs-postgresml.md"` this is not present in the file tree on the left. And the expand directory icon also hangs for some reason?
2. In your [allsamples-onlyfindings-noresources.json.txt](https://github.com/nexB/scancode-workbench/files/13883214/allsamples-onlyfindings-noresources.json.txt) example, when we import this, nothing happens are there are no resources. I would like to see something to indicate that there was no resources in the scan and so we can't show anything.

**Comment by OmkarPh** [comment]
> 1. In the only-findings scan, the file-tree is not behaving correctly for nested directories (as the corresponding parent directories are missing?) should we populate missing parent directories ourself while importing the scan? Example resource: `"postgresml-2.8.1/pgml-cms/docs/resources/benchmarks/mindsdb-vs-postgresml.md"` this is not present in the file tree on the left. And the expand directory icon also hangs for some reason?

Thank you for pointing this out, there was an issue with handling files in batches (for large scans)
I've fixed it. Should work fine now, see
image

**Comment by OmkarPh** [comment]
> 2. In your [allsamples-onlyfindings-noresources.json.txt](https://github.com/nexB/scancode-workbench/files/13883214/allsamples-onlyfindings-noresources.json.txt) example, when we import this, nothing happens are there are no resources. I would like to see something to indicate that there was no resources in the scan and so we can't show anything.

Sure, I'll add a warning/error snackbar with this message
But, should we abort importing such scans or load all views with empty data?

**Comment by AyanSinhaMahapatra** [comment]
> But, should we abort importing such scans or load all views with empty data?

If there's no data at all (here I mainly mean no file data, as other codebase level attributes are atleast option-dependent) there's no use showing empty views, so it's fine if we abort importing and show the message there.

**Comment by OmkarPh** [comment]
Thanks for the feedback @AyanSinhaMahapatra 
I've updated the PR

**Review by AyanSinhaMahapatra — APPROVED** [review]
@OmkarPh LGTM! Thanks++
The issues mentioned above are fixed now and this is ready to merge.
Please release too :rocket:

**Pull request merged**
