### PR TITLE
Removed conclusions module

### LINKED ISSUE #512: Remove editable conclusions features
### Description
We should remove the ability to enter conclusions. This should be instead a new design that would be best based on ScanCode.io and automation.

### PR DESCRIPTION
**Pull request by OmkarPh**
Fixes #512 

Signed-off-by: Omkar Phansopkar <omkarphansopkar@gmail.com>

### CODE REVIEW

**Comment by OmkarPh** [comment]
Hi @pombredanne 
I've removed conclusions from the application.
Should I remove from the docs too

**Comment by AyanSinhaMahapatra** [comment]
Looks LGTM to me. Thanks @OmkarPh! 

I could build and use workbench all right from this branch (with no sign of the conclusions module). 

Any idea why the CI didn't run here but it did in #519 ?

**Comment by AyanSinhaMahapatra** [comment]
Looks LGTM to me. Thanks @OmkarPh! 

I could build and use workbench all right from this branch (with no sign of the conclusions module). 

Any idea why the CI didn't run here but it did in #519 ?

**Comment by OmkarPh** [comment]
> Any idea why the CI didn't run here but it did in #519 ?

I'm clueless 🤔

**Comment by pombredanne** [comment]
LGTM. We need to reinstate the CI run though.

**Review by steven-esser — APPROVED** [review]

**Pull request merged**
