### PR TITLE
Updation in the Building requirements section for MacOS

### PR DESCRIPTION
**Pull request by Pushpit07**

### CODE REVIEW

**Review by steven-esser — CHANGES_REQUESTED** [review]
@Pushpit07 Thanks for the contribution. Please use a commit sign-off and rebase your commits into a single one.

**Comment by Pushpit07** [comment]
Done

**Comment by Pushpit07** [comment]
By the way, is this repository still active? Feels like contributions haven't been made since a long time

**Comment by steven-esser** [comment]
@Pushpit07 it is still active and maintained. We tend to develop features for this application slower, as we are primarily a python shop and lack a lot of JavaScript expertise. We have also moved a lot of development effort towards the server side, with https://github.com/nexB/scancode.io

However, there is still a place for a dedicated desktop application to view scancode-toolkit scan results. We continue to welcome all contributions and contributors, especially those with an interest in nodejs :)

**Review by steven-esser — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
