### PR TITLE
Removing double scrollbar on clicking hide all button

### LINKED ISSUE #473: Double scroll bar on clicking the Hide all button in ScanCode Data Table
### Description
**Bug Report**
In the ScanCode Data Table, when I click the **Hide All** button, the application shows double scrollbar at the bottom of the page. I am attaching a screenshot for your reference
Screenshot from 2021-01-07 03-31-24

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Linux)
* What version of scancode-workbench are you running on? (v3.1.1)
* What version of scancode-toolkit was used to generate the scan file?(Sample json file)

### PR DESCRIPTION
**Pull request by pranav1698**
This removes unwanted horizontal scrollbar on clicking the Hide all button,
Also, improvements in the styling of the css code as recommended by Prettier code extension

Fixes #473

@majurg please review

### CODE REVIEW

**Review by steven-esser — APPROVED** [review]

**Review by Vishal-raj-1 — APPROVED** [review]

**Review by steven-esser — CHANGES_REQUESTED** [review]
@pranav1698 Oops, looks like there is actually one linting error (see travis results for more details):
```
1 failing

  1) ESLint

       validates /home/travis/build/nexB/scancode-workbench/assets/app/js/controllers/conclusionDialog.js:

     AssertionError: 210:23 Strings must use singlequote - quotes

232:23 Strings must use singlequote - quotes

253:23 Strings must use singlequote - quotes

275:23 Strings must use singlequote - quotes

309:23 Strings must use singlequote - quotes

334:23 Strings must use singlequote - quotes

361:23 Strings must use singlequote - quotes

382:23 Strings must use singlequote - quotes

      at Context.it (test/eslint.test.js:41:14)
```

Looks like this is a result of your linting tool. If you could revert these changes that would be great.

**Comment by Vishal-raj-1** [comment]
@pranav1698 You can pull the changes from developer branch. I have solved this lint error.

**Comment by Vishal-raj-1** [comment]
@pranav1698 are you looking forward to this PR !! @majurg Can I solve this issue, as this PR contains conflicting files.

**Comment by steven-esser** [comment]
@Vishal-raj-1 Since we already have working code, its best if you find another issue to work on. 

@pranav1698 Ping :)

**Comment by pranav1698** [comment]
Yeah, was not working on this because this was already solved by another PR
Sorry, forgot to close it

**Comment by steven-esser** [comment]
@pranav1698 Was it? Maybe I am missing something, but I believe your PR was the only solution so far.

**Pull request closed without merging**
